// Code generated by goagen v1.1.0, command line:
// $ main
//
// API "ferrariserver": worker Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ListWorkerPath computes a request path to the list action of worker.
func ListWorkerPath() string {

	return fmt.Sprintf("/v1/workers")
}

// ListWorker makes a request to the list action endpoint of the worker resource
func (c *Client) ListWorker(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListWorkerRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkerRequest create the request corresponding to the list action endpoint of the worker resource.
func (c *Client) NewListWorkerRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
